// js/audio-and-video-calls/react/src/App.js
import React from 'react';
import {
    BrowserRouter as Router,
    Switch,
    Route,
    Link
} from "react-router-dom";
import RoomCall from "./RoomCall";
import WebrtcCall from "./WebrtcCall";
import PhoneCall from "./PhoneCall";

function App() {
    return (
        <Router>
            <div>
                <nav>
                    <Link to="/webrtc-call">WebRTC Call</Link> | <Link to="/phone-call">Phone Call</Link> | <Link to="/room-call">Room Call</Link>
                </nav>
                <hr/>
                <Switch>
                    <Route path="/webrtc-call">
                        <WebrtcCall/>
                    </Route>
                    <Route path="/phone-call">
                        <PhoneCall/>
                    </Route>
                    <Route path="/room-call">
                        <RoomCall/>
                    </Route>
                    <Route path="/">
                        <WebrtcCall/>
                    </Route>
                </Switch>
            </div>
        </Router>
    );
}

export default App;

// js/audio-and-video-calls/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
}

<div>
  <nav>
    <a routerLink="/webrtc-call" routerLinkActive="active">WebRTC Call</a> | <a routerLink="/phone-call" routerLinkActive="active">Phone Call </a> | <a routerLink="/room-call" routerLinkActive="active">Room Call</a>
  </nav>
  <hr>
  <router-outlet></router-outlet>
</div>
