// js/application-calls/angular/src/app/components/role/role.component.ts
import {Component} from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'app-role',
  templateUrl: './role.component.html'
})
export class RoleComponent {
  constructor(private router: Router) {}

  loginCustomer() {
    this.router.navigate(['/customer']);
  }

  loginAgent() {
    this.router.navigate(['/agent']);
  }
}

<div>
  <div>
    <button (click)="loginCustomer()">Customer Login</button>
    <button (click)="loginAgent()">Agent Login</button>
  </div>
</div>

// js/application-calls/react/src/Role.js
import React, {Component} from "react";

class Role extends Component {
    constructor(props) {
        super(props);
        this.state = { };
    }

    loginCustomer = () => {
        window.location.href = '/customer';
    }

    loginAgent = () => {
        window.location.href = '/agent';
    }

    render = () => {
        return (
            <div>
                <button onClick={() => this.loginCustomer()}>Customer Login</button>
                <button onClick={() => this.loginAgent()}>Agent Login</button>
            </div>
        )
    }
}

export default Role;
