// js/angular/src/app/components/webrtc-call/webrtc-call.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {
  WebrtcCallOptions,
  InfobipRTC,
  createInfobipRtc,
  WebrtcCall,
  IncomingWebrtcCall,
  CallsApiEvent
} from 'infobip-rtc';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-call',
  templateUrl: './webrtc-call.component.html'
})
export class WebrtcCallComponent implements OnInit {
  @ViewChild('remoteAudio') remoteAudio: HTMLAudioElement;
  @ViewChild('localCameraVideo') localCameraVideo: HTMLVideoElement;
  @ViewChild('localScreenShare') localScreenShare: HTMLVideoElement;
  @ViewChild('remoteCameraVideo') remoteCameraVideo: HTMLVideoElement;
  @ViewChild('remoteScreenShare') remoteScreenShare: HTMLVideoElement;

  title = 'Infobip RTC Call Showcase';

  destination = '';
  infobipRTC: InfobipRTC = null;
  activeCall: WebrtcCall = null;
  identity = '';
  status = '';
  isCallEstablished = false;
  isIncomingCall = false;
  iPhoneOrIpad = false;

  constructor(private httpClient: HttpClient) {
    this.connectInfobipRTC();
  }

  ngOnInit = () => {
    const userAgent = window.navigator.userAgent;
    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
      this.iPhoneOrIpad = true;
      // @ts-ignore
      this.remoteCameraVideo.nativeElement.muted = true;
    }
  }

  unmuteVideo = () => {
    // @ts-ignore
    this.remoteVideo.nativeElement.muted = false;
  }

  connectInfobipRTC = () => {
    this.httpClient.post('http://localhost:8080/token', {})
      .toPromise()
      .then((response: Response) => {
        // @ts-ignore
        this.infobipRTC = createInfobipRtc(response.token, { debug: true });
        this.infobipRTC.on('connected', event => {
          this.identity = event.identity;
          console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
        });
        this.infobipRTC.on('disconnected', event => {
          console.warn('Disconnected from Infobip RTC Cloud.');
        });
        this.infobipRTC.connect();
        this.listenForIncomingWebrtcCall();
      })
  };

  listenForIncomingWebrtcCall = () => {
    this.infobipRTC.on('incoming-webrtc-call', incomingCallEvent => {
      const incomingWebrtcCall = incomingCallEvent.incomingCall;
      console.log('Received incoming call from: ' + incomingWebrtcCall.source().identifier);

      this.activeCall = incomingWebrtcCall;
      this.isIncomingCall = true;
      this.status = 'Incoming ' + (incomingWebrtcCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingWebrtcCall.source().identifier;

      this.listenForWebrtcCallEvents();
    });
  };

  listenForWebrtcCallEvents = () => {
    this.activeCall.on(CallsApiEvent.RINGING, () => {
      this.status = 'Ringing...';
      console.log('Call is ringing...');
    });
    this.activeCall.on(CallsApiEvent.ESTABLISHED, event => {
      this.status = 'Call established with: ' + this.activeCall.counterpart().identifier;
      console.log('Call established with ' + this.activeCall.counterpart().identifier);
      this.isCallEstablished = true;
      this.setMediaStream(this.remoteAudio, event.stream);
    });
    this.activeCall.on(CallsApiEvent.HANGUP, event => {
      this.status = 'Call finished' + event.errorCode.name;
      console.log('Call finished' + event.errorCode.name);
      this.removeAllMediaStreams();
      this.setValuesAfterCall();
    });
    this.activeCall.on(CallsApiEvent.ERROR, event => {
      console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
    });

    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_ADDED, event => {
      this.status = 'Local camera video has been added';
      console.log('Local camera video has been added');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, event => {
      this.status = 'Local camera video has been updated';
      console.log('Local camera video has been updated');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, () => {
      this.status = 'Local camera video has been removed';
      console.log('Local camera video has been removed');
      this.setMediaStream(this.localCameraVideo, null);
    });

    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_ADDED, event => {
      this.status = 'Local screenshare has been added';
      console.log('Local screenshare has been added');
      this.setMediaStream(this.localScreenShare, event.stream);
    });
    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_REMOVED, () => {
      this.status = 'Local screenshare has been removed';
      console.log('Local screenshare has been removed');
      this.setMediaStream(this.localScreenShare, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_ADDED, event => {
      this.status = 'Remote camera video has been added';
      console.log('Remote camera video has been added');
      this.setMediaStream(this.remoteCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_REMOVED, () => {
      this.status = 'Remote camera video has been removed';
      console.log('Remote camera video has been added');
      this.setMediaStream(this.remoteCameraVideo, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_SCREEN_SHARE_ADDED, event => {
      this.status = 'Remote screenshare has been added';
      console.log('Remote screenshare has been added');
      this.setMediaStream(this.remoteScreenShare, event.stream);
    });
    this.activeCall.on(CallsApiEvent.REMOTE_SCREEN_SHARE_REMOVED, () => {
      this.status = 'Remote screenshare has been removed';
      console.log('Remote screenshare has been removed');
      this.setMediaStream(this.remoteScreenShare, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_MUTED, () => {
      this.status = 'Remote participant has been muted';
      console.log('Remote participant has been muted');
    });
    this.activeCall.on(CallsApiEvent.REMOTE_UNMUTED, () => {
      this.status = 'Remote participant has been unmuted';
      console.log('Remote participant has been unmuted');
    });
  };

  removeAllMediaStreams = () => {
    // @ts-ignore
    this.remoteAudio.nativeElement.srcObject = null;
    // @ts-ignore
    this.localCameraVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.localScreenShare.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteCameraVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteScreenShare.nativeElement.srcObject = null;
  }

  setMediaStream(element, stream) {
    element.nativeElement.srcObject = stream;
  }

  onChange = (event) => {
    this.destination = event.target.value;
  };

  call = (video = false) => {
    if (this.destination) {
      const webrtcCallOptions = WebrtcCallOptions.builder()
        .setVideo(video)
        .build();

      this.activeCall = this.infobipRTC.callWebrtc(this.destination, webrtcCallOptions);

      this.listenForWebrtcCallEvents();
    }
  };

  hangup = () => {
    this.activeCall.hangup();
  };

  accept = () => {
    (this.activeCall as IncomingWebrtcCall).accept();
  };

  decline = () => {
    (this.activeCall as IncomingWebrtcCall).decline();
  };

  shouldShowButtonsOnIncomingCall = () => {
    return !this.isCallEstablished && this.isIncomingCall;
  };

  shouldDisableHangupButton = () => {
    return !this.activeCall || (!this.isCallEstablished && this.isIncomingCall);
  };

  toggleCameraVideo = () => {
    this.activeCall.cameraVideo(!this.activeCall.hasCameraVideo());
  }

  toggleShareScreen = () => {
    this.activeCall.screenShare(!this.activeCall.hasScreenShare());
  }

  private setValuesAfterCall = () => {
    this.status = null;
    this.activeCall = null;
    this.isCallEstablished = false;
    this.isIncomingCall = false;
  }

  shouldShowLocalVideos = () => {
    return this.activeCall && (this.activeCall.hasCameraVideo() || this.activeCall.hasScreenShare());
  }

  shouldShowRemoteVideos = () => {
    return this.activeCall && (this.activeCall.hasRemoteCameraVideo() || this.activeCall.hasRemoteScreenShare());
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Infobip RTC Showcase</title>
</head>
<body>
  <div>
    <h2>{{title}}</h2>
    <h4>Logged as: <span>{{identity || 'None'}}</span></h4>
  </div>

  <audio #remoteAudio autoPlay></audio>

  <input type="text" (change)="onChange($event)" placeholder="Enter destination to call..."/>
  <br/><br/>

  <button [disabled]="activeCall" (click)="call(false)">Call</button>
  <button [disabled]="activeCall" (click)="call(true)">Video Call</button>
  <br/><br/>

  <button [disabled]="!activeCall" (click)="toggleCameraVideo()">Toggle Camera Video</button>
  <button [disabled]="!activeCall" (click)="toggleShareScreen()">Toggle Share Screen</button>

  <h4><span>{{status}}</span></h4>
  <br/><br/>

  <div [hidden]="!shouldShowButtonsOnIncomingCall()">
    <button (click)="accept()">Accept</button>
    <button (click)="decline()">Decline</button>
    <br/><br/>
  </div>

  <button [disabled]="shouldDisableHangupButton()" (click)="hangup()">Hangup</button>
  <br/><br/>

  <div *ngIf="iPhoneOrIpad">
    <button (click)="unmuteVideo()">Tap to Unmute</button>
    <br/><br/>
  </div>

  <div [hidden]="!shouldShowRemoteVideos()">
    <h3>Remote video/screenshare</h3>
    <video #remoteCameraVideo autoplay muted
           style="object-fit: cover"
           width="300" height="300">
    </video>
    <video #remoteScreenShare autoplay
           style="object-fit: cover"
           width="300" height="300">
    </video>
  </div>

  <div [hidden]="!shouldShowLocalVideos()">
    <h3>Local video/screenshare</h3>
    <video #localCameraVideo autoplay muted
           style="object-fit: cover"
           width="300" height="300">
    </video>
    <video #localScreenShare autoplay
           style="object-fit: cover"
           width="300" height="300">
    </video>
  </div>
</body>
</html>

// js/react/src/WebrtcCall.js
import React, {Component} from "react";
import {CallsApiEvent, createInfobipRtc, WebrtcCallOptions} from "infobip-rtc";
import httpClient from "axios";

class WebrtcCall extends Component {

    constructor(props) {
        super(props);
        this.state = {
            title: 'Infobip RTC Call Showcase',
            destination: '',
            infobipRTC: null,
            activeCall: null,
            identity: '',
            status: '',
            isIncomingCall: false,
            isCallEstablished: false,
            isIphoneOrIpad: !!(window.navigator.userAgent.match(/iPad/i) || window.navigator.userAgent.match(/iPhone/i))
        };

        this.connectInfobipRTC();
    }

    connectInfobipRTC = async () => {
        httpClient.post('http://localhost:8080/token')
            .then((response) => {
                const token = response.data.token

                this.setState((state) => {
                    state.infobipRTC = createInfobipRtc(token, { debug: true });
                    state.infobipRTC.on('connected',  (event) => {
                        this.setState({identity: event.identity});
                        console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
                    });
                    state.infobipRTC.on('disconnected', function (event) {
                        console.warn('Disconnected from Infobip RTC Cloud.');
                    });
                    state.infobipRTC.connect();
                    this.listenForIncomingCall();
                    return state;
                });
            })
            .catch(err => {
                console.error(err);
            });
    };

    listenForIncomingCall = () => {
        let that = this;
        this.state.infobipRTC.on('incoming-webrtc-call', function (incomingCallEvent) {
            const incomingCall = incomingCallEvent.incomingCall;
            console.log('Received incoming call from: ' + incomingCall.counterpart().identifier);

            that.setState({
                activeCall: incomingCall,
                isIncomingCall: true,
                status: 'Incoming ' + (incomingCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingCall.counterpart().identifier
            });

            that.setCallEventHandlers(incomingCall);
        });
    }

    setCallEventHandlers = (call) => {
        let that = this;
        call.on(CallsApiEvent.RINGING, function () {
            that.setState({status: 'Ringing...'});
            console.log('Call is ringing...');
        });
        call.on(CallsApiEvent.ESTABLISHED, function (event) {
            that.setState({
                status: 'Call established with: ' + that.state.activeCall.counterpart().identifier,
                isCallEstablished: true
            });
            console.log('Call established with ' + that.state.activeCall.counterpart().identifier);
            that.setMediaStream(that.refs.remoteAudio, event.stream);
        });
        call.on(CallsApiEvent.HANGUP, function (event) {
            that.setState({status: 'Call finished: ' + event.errorCode.name});
            console.log('Call finished: ' + event.errorCode.name);
            that.removeAllMediaStreams();
            that.setValuesAfterCall();
        });

        call.on(CallsApiEvent.ERROR, function (event) {
            console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        });

        call.on(CallsApiEvent.CAMERA_VIDEO_ADDED, function (event) {
            that.setState({status: 'Local camera video has been added'});
            console.log('Local camera video has been added');
            that.setMediaStream(that.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, function (event) {
            that.setState({status: 'Local camera video has been updated'});
            console.log('Local camera video has been updated');
            that.setMediaStream(that.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, function () {
            that.setState({status: 'Local camera video has been removed'});
            console.log('Local camera video has been removed');
            that.setMediaStream(that.refs.localCameraVideo, null);
        });

        call.on(CallsApiEvent.SCREEN_SHARE_ADDED, function (event) {
            that.setState({status: 'Local screenshare has been added'});
            console.log('Local screenshare has been added');
            that.setMediaStream(that.refs.localScreenShare, event.stream);
        });
        call.on(CallsApiEvent.SCREEN_SHARE_REMOVED, function () {
            that.setState({status: 'Local screenshare has been removed'});
            console.log('Local screenshare has been removed');
            that.setMediaStream(that.refs.localScreenShare, null);
        });

        call.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_ADDED, function (event) {
            that.setState({status: 'Remote camera video has been added'});
            console.log('Remote camera video has been added');
            that.setMediaStream(that.refs.remoteCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_REMOVED, function () {
            that.setState({status: 'Remote camera video has been removed'});
            console.log('Remote camera video has been removed');
            that.setMediaStream(that.refs.remoteCameraVideo, null);
        });

        call.on(CallsApiEvent.REMOTE_SCREEN_SHARE_ADDED, function (event) {
            that.setState({status: 'Remote screenshare has been added'});
            console.log('Remote screenshare has been added');
            that.setMediaStream(that.refs.remoteScreenShare, event.stream);
        });
        call.on(CallsApiEvent.REMOTE_SCREEN_SHARE_REMOVED, function () {
            that.setState({status: 'Remote screenshare has been removed'});
            console.log('Remote screenshare has been removed');
            that.setMediaStream(that.refs.remoteScreenShare, null);
        });

        call.on(CallsApiEvent.REMOTE_MUTED, function () {
            that.setState({status: 'Remote participant has been muted'});
            console.log('RRemote participant has been muted');
        });
        call.on(CallsApiEvent.REMOTE_UNMUTED, function () {
            that.setState({status: 'Remote participant has been unmuted'});
            console.log('Remote participant has been unmuted');
        });
    }

    setMediaStream = (element, stream) => {
        element.srcObject = stream;
    }

    removeAllMediaStreams = () => {
        this.refs.localCameraVideo.srcObject = null;
        this.refs.localScreenShare.srcObject = null;
        this.refs.remoteCameraVideo.srcObject = null;
        this.refs.remoteScreenShare.srcObject = null;
        this.refs.remoteAudio.srcObject = null;
    }

    handleChange = (event) => {
        const dest = event.target.value;
        this.setState({destination: dest});
    };

    call = (video = false) => {
        if (this.state.destination) {
            let webrtcCallOptions = WebrtcCallOptions.builder()
                .setVideo(video)
                .build();

            const activeCall = this.state.infobipRTC.callWebrtc(this.state.destination, webrtcCallOptions);
            this.setCallEventHandlers(activeCall);
            this.setState({activeCall: activeCall});
        }
    };

    accept = () => {
        this.state.activeCall.accept();
    };

    decline = () => {
        this.state.activeCall.decline();
    };

    hangup = () => {
        this.state.activeCall.hangup();
    };

    shouldShowButtonsOnIncomingCall = () => {
        return this.state.isIncomingCall && !this.state.isCallEstablished;
    }

    shouldDisableHangupButton = () => {
        return !this.state.activeCall || (!this.state.isCallEstablished && this.state.isIncomingCall);
    }

    hasLocalVideos = () => {
        return this.state.activeCall && (this.state.activeCall.hasCameraVideo() || this.state.activeCall.hasScreenShare());
    }

    hasRemoteVideos = () => {
        return this.state.activeCall && (this.state.activeCall.hasRemoteCameraVideo() || this.state.activeCall.hasRemoteScreenShare());
    }

    setValuesAfterCall = () => {
        this.setState({
            activeCall: null,
            isCallEstablished: false,
            isIncomingCall: false,
            status: ''
        });
    }

    render = () => {
        return (
            <div>
                <h2><span>{this.state.title}</span></h2>
                <h4>Logged as: <span>{this.state.identity}</span></h4>

                <audio ref="remoteAudio" autoPlay/>

                <input type="text" value={this.state.destination} onChange={this.handleChange}
                       placeholder="Enter destination to call..."/>
                <br/> <br/>

                <button disabled={this.state.activeCall} onClick={() => this.call(false)}>Call</button>
                <button disabled={this.state.activeCall} onClick={() => this.call(true)}>Video Call</button>
                <br/><br/>

                <button disabled={!this.state.activeCall}
                        onClick={() => this.state.activeCall.cameraVideo(!this.state.activeCall.hasCameraVideo())}>
                    Toggle Camera Video</button>
                <button disabled={!this.state.activeCall}
                        onClick={() => this.state.activeCall.screenShare(!this.state.activeCall.hasScreenShare())}>
                        Toggle Screen Share</button>

                <h4><span>{this.state.status}</span></h4>

                {this.shouldShowButtonsOnIncomingCall() &&
                    <div>
                        <button onClick={this.accept}>Accept</button>
                        <button onClick={this.decline}>Decline</button>
                        <br/><br/>
                    </div>}

                <button disabled={this.shouldDisableHangupButton()}
                        onClick={this.hangup}>Hangup
                </button>
                <br/><br/>

                {this.state.isIphoneOrIpad && (<button onClick={() => { this.refs.remoteVideo.muted = false }}>Tap to Unmute</button>)}

                <div hidden={this.hasRemoteVideos() ? '' : 'hidden'}>
                    <h3>Remote video/screenshare</h3>
                    <video ref="remoteCameraVideo" autoPlay
                           muted={this.state.isIphoneOrIpad}
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                    <video ref="remoteScreenShare" autoPlay
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                </div>

                <div hidden={this.hasLocalVideos() ? '' : 'hidden'}>
                    <h3>Local video/screenshare</h3>
                    <video ref="localCameraVideo" autoPlay muted
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                    <video ref="localScreenShare" autoPlay
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                </div>
            </div>
        )
    }
}

export default WebrtcCall;
