// js/audio-and-video-calls/react/src/PhoneCall.js
import React, {Component} from "react";
import {AudioQualityMode, CallsApiEvent, createInfobipRtc, InfobipRTCEvent, PhoneCallOptions} from "infobip-rtc";
import httpClient from "axios";

const audioQualityModes = {
    "Low": AudioQualityMode.LOW_DATA,
    "Auto": AudioQualityMode.AUTO,
    "High": AudioQualityMode.HIGH_QUALITY
}

class PhoneCall extends Component {

    constructor(props) {
        super(props);
        this.state = {
            title: 'Infobip RTC Call Showcase',
            destination: '',
            infobipRTC: null,
            activeCall: null,
            identity: '',
            status: '',
            audioInputDevices: [],
            selectedAudioQualityMode: "Auto"
        };

        this.connectInfobipRTC();
    }

    connectInfobipRTC = async () => {
        httpClient.post('http://localhost:8080/token')
            .then((response) => {
                const token = response.data.token

                this.setState((state) => {
                    state.infobipRTC = createInfobipRtc(token, { debug: true });
                    state.infobipRTC.on(InfobipRTCEvent.CONNECTED, event => {
                        this.setState({identity: event.identity});
                        console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
                    });
                    state.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
                        console.warn('Disconnected from Infobip RTC Cloud.');
                    });
                    state.infobipRTC.connect();
                    this.loadAudioDevices();
                    return state;
                });
            })
            .catch(err => {
                console.error(err);
            });
    };

    loadAudioDevices = () => {
        this.state.infobipRTC.getAudioInputDevices().then(inputDevices => this.setState({audioInputDevices: inputDevices}));
    }

    setCallEventHandlers = (call) => {
        call.on(CallsApiEvent.RINGING, () => {
            this.setState({status: 'Ringing...'});
            console.log('Call is ringing...');
        });
        call.on(CallsApiEvent.ESTABLISHED, event => {
            this.setState({status: 'Call established with: ' + this.state.activeCall.counterpart().identifier});
            console.log('Call established with ' + this.state.activeCall.counterpart().identifier);
            this.setMediaStream(this.refs.remoteAudio, event.stream);
        });
        call.on(CallsApiEvent.HANGUP, event => {
            this.setState({status: 'Call finished: ' + event.name});
            console.log('Call finished: ' + event.name);
            this.setMediaStream(this.refs.remoteAudio, null);
            this.setValuesAfterCall();
        });
        call.on(CallsApiEvent.ERROR, event => {
            console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        });
        call.on(CallsApiEvent.RECONNECTING, () => {
            this.setState({status: 'Reconnecting...'});
            console.log('Reconnecting...');
        });
        call.on(CallsApiEvent.RECONNECTED, () => {
            this.setState({status: 'Call established with: ' + this.state.activeCall.counterpart().identifier});
            console.log('Reconnected');
        });
    }

    setMediaStream = (element, stream) => {
        element.srcObject = stream;
    }

    handleChange = (event) => {
        const dest = event.target.value;
        this.setState({destination: dest});
    };

    callPhone = () => {
        if (this.state.destination) {
            let phoneCallOptions = PhoneCallOptions.builder()
                .setFrom('33712345678')
                .setAutoReconnect(true)
                .build();
            const activeCall = this.state.infobipRTC.callPhone(this.state.destination, phoneCallOptions);
            this.setCallEventHandlers(activeCall);
            this.setState({ activeCall: activeCall });
        }
    };

    hangup = () => {
        this.state.activeCall.hangup();
    };

    shouldDisableHangupButton = () => {
        return !this.state.activeCall || (!this.state.isCallEstablished && this.state.isIncomingCall);
    }

    setValuesAfterCall = () => {
        this.setState({
            activeCall: null,
            status: '',
            selectedAudioQualityMode: "Auto"
        });
    }

    onAudioInputDeviceChange = async (event) => {
        const deviceId = event.target.value;
        const {activeCall} = this.state;
        if (!!activeCall) {
            await activeCall.setAudioInputDevice(deviceId);
        }
    }

    onAudioQualityChange = event => {
        const audioQuality = event.target.value;
        const {activeCall} = this.state;
        this.setState({selectedAudioQualityMode: audioQuality});

        if (!!activeCall) {
            activeCall.setAudioQualityMode(audioQualityModes[audioQuality]);
        }
    }

    render = () => {
        const {
            title,
            identity,
            destination,
            activeCall,
            status,
            audioInputDevices,
            selectedAudioQualityMode
        } = this.state;

        return (
            <div>
                <h2><span>{title}</span></h2>
                <h4>Logged as: <span>{identity}</span></h4>

                <audio ref="remoteAudio" autoPlay/>

                <input type="text" value={destination} onChange={this.handleChange}
                       placeholder="Enter phone number to call..."/>
                <br/> <br/>

                <button disabled={activeCall} onClick={() => this.callPhone()}>Call</button>

                <h4><span>{status}</span></h4>

                <button disabled={this.shouldDisableHangupButton()}
                        onClick={this.hangup}>Hangup
                </button>
                <br/><br/>

                {!!activeCall &&
                    <>
                        <label htmlFor={"audio-input-device-select"}>Choose audio input device:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioInputDeviceChange}>
                            {audioInputDevices.map(device => <option id={device.deviceId} value={device.deviceId}>{device.label || device.deviceId}</option>)}
                        </select>
                        <br/><br/>

                        <label htmlFor={"audio-input-device-select"}>Choose audio quality mode:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioQualityChange} value={selectedAudioQualityMode}>
                            {Object.keys(audioQualityModes).map(mode => <option id={mode} value={mode}>{mode}</option>)}
                        </select>
                        <br/><br/>
                    </>
                }
            </div>
        )
    }
}

export default PhoneCall;

// js/audio-and-video-calls/angular/src/app/components/phone-call/phone-call.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {
  AudioQualityMode,
  CallsApiEvent,
  createInfobipRtc,
  InfobipRTC,
  InfobipRTCEvent,
  PhoneCall,
  PhoneCallOptions
} from 'infobip-rtc';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-call',
  templateUrl: './phone-call.component.html'
})
export class PhoneCallComponent implements OnInit {
  @ViewChild('remoteAudio') remoteAudio: HTMLAudioElement;

  title = 'Infobip RTC Call Showcase';

  destination = '';
  infobipRTC: InfobipRTC = null;
  activeCall: PhoneCall = null;
  identity = '';
  status = '';
  isCallEstablished = false;
  isOutgoingCall = false;
  audioInputDevices: MediaDeviceInfo[] = [];
  selectedAudioInputDevice: string;
  audioQualityModes: { [name: string]: AudioQualityMode } = {
    Low: AudioQualityMode.LOW_DATA,
    Auto: AudioQualityMode.AUTO,
    High: AudioQualityMode.HIGH_QUALITY
  }
  selectedAudioQualityMode = 'Auto';

  constructor(private httpClient: HttpClient) {
    this.connectInfobipRTC();
  }

  ngOnInit = () => {
  }

  connectInfobipRTC = () => {
    this.httpClient.post('http://localhost:8080/token', {})
      .toPromise()
      .then((response: Response) => {
        // @ts-ignore
        this.infobipRTC = createInfobipRtc(response.token, { debug: true });
        this.infobipRTC.on(InfobipRTCEvent.CONNECTED, event => {
          this.identity = event.identity;
          console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
        });
        this.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
          console.warn('Disconnected from Infobip RTC Cloud.');
        });
        this.infobipRTC.connect();
        this.loadAudioDevices()
      })
  };

  loadAudioDevices = () => {
    this.infobipRTC.getAudioInputDevices().then(inputDevices => {
      this.audioInputDevices = inputDevices;
      this.selectedAudioInputDevice = inputDevices[0].deviceId
    });
  }

  listenForPhoneCallEvents = () => {
    this.activeCall.on(CallsApiEvent.RINGING, () => {
      this.status = 'Ringing...';
      console.log('Call is ringing...');
    });
    this.activeCall.on(CallsApiEvent.ESTABLISHED, event => {
      this.status = 'Call established with: ' + this.destination;
      console.log('Call established with ' + this.destination);
      this.isCallEstablished = true;
      this.setMediaStream(this.remoteAudio, event.stream);
    });
    this.activeCall.on(CallsApiEvent.HANGUP, event => {
      this.status = 'Call finished: ' + event.errorCode.name;
      console.log('Call finished: ' + event.errorCode.name);
      this.removeMediaStream();
      this.setValuesAfterCall();
    });
    this.activeCall.on(CallsApiEvent.ERROR, event => {
      console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
    });
    this.activeCall.on(CallsApiEvent.RECONNECTING, () => {
      this.status = 'Reconnecting...';
      console.log('Reconnecting...');
    });
    this.activeCall.on(CallsApiEvent.RECONNECTED, () => {
      this.status = 'Call established with: ' + this.destination;
      console.log('Reconnected');
    });
  };

  setMediaStream = (element, stream) => {
    element.nativeElement.srcObject = stream;
  }

  removeMediaStream = () => {
    // @ts-ignore
    this.remoteAudio.nativeElement.srcObject = null;
  }

  onChange = (event) => {
    this.destination = event.target.value;
  };

  callPhoneNumber = () => {
    if (this.destination) {
      const phoneCallOptions = PhoneCallOptions.builder()
        .setFrom('33712345678')
        .setAutoReconnect(true)
        .build();

      this.activeCall = this.infobipRTC.callPhone(this.destination, phoneCallOptions);

      this.listenForPhoneCallEvents();
    }
  };

  hangup = () => {
    this.activeCall.hangup();
  };

  shouldDisableHangupButton = () => {
    return !this.activeCall || !this.isCallEstablished;
  };

  onAudioInputDeviceChange = async () => {
    if (this.activeCall != null) {
      await this.activeCall.setAudioInputDevice(this.selectedAudioInputDevice)
    }
  }

  onAudioQualityChange = () => {
    if (this.activeCall != null) {
      this.activeCall.setAudioQualityMode(this.audioQualityModes[this.selectedAudioQualityMode])
    }
  }

  private setValuesAfterCall = () => {
    this.status = null;
    this.activeCall = null;
    this.isCallEstablished = false;
    this.isOutgoingCall = false;
    this.selectedAudioQualityMode = 'Auto'
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Infobip RTC Showcase</title>
</head>
<body>
<div>
  <h2>{{title}}</h2>
  <h4>Logged as: <span>{{identity || 'None'}}</span></h4>
</div>
<div>
  <audio #remoteAudio autoPlay></audio>

  <input type="text" (change)="onChange($event)" placeholder="Enter phone number to call..."/>
  <br/><br/>

  <button [disabled]="activeCall" (click)="callPhoneNumber()">Call</button>
  <br/><br/>

  <h4><span>{{status}}</span></h4>
  <br/><br/>

  <button [disabled]="shouldDisableHangupButton()" (click)="hangup()">Hangup</button>
  <br/><br/>

  <ng-container *ngIf="!!activeCall">
    <label for="audio-input-device-select">Choose audio input device:</label>
    <select id="audio-input-device-select" [(ngModel)]="selectedAudioInputDevice" (change)="onAudioInputDeviceChange()">
      <option *ngFor="let device of audioInputDevices" [value]="device.deviceId">{{device.label || device.deviceId}}</option>
    </select>
    <br/><br/>

    <label for="audio-quality-mode-select">Choose audio quality mode:</label>
    <select id="audio-quality-mode-select" [(ngModel)]="selectedAudioQualityMode" (change)="onAudioQualityChange()">
      <option *ngFor="let mode of audioQualityModes | keyvalue" [value]="mode.key">{{mode.key}}</option>
    </select>
    <br/><br/>
  </ng-container>
</div>
</body>
</html>
