// js/application-calls/react/src/Agent.js
import React, {Component} from "react";
import {
    ApplicationCallOptions,
    AudioQualityMode,
    CallsApiEvent,
    createInfobipRtc,
    InfobipRTCEvent,
    NetworkQuality
} from "infobip-rtc";
import httpClient from "axios";

const audioQualityModes = {
    'Low': AudioQualityMode.LOW_DATA,
    'Auto': AudioQualityMode.AUTO,
    'High': AudioQualityMode.HIGH_QUALITY
}

class Agent extends Component {
    constructor(props) {
        super(props);
        this.state = {
            infobipRTC: null,
            activeCall: null,
            identity: '',
            status: '',
            isIncomingCall: false,
            isCallEstablished: false,
            participants: [],
            audioInputDevices: [],
            selectedAudioQualityMode: 'Auto'
        };

        this.connectInfobipRTC();
    }

    connectInfobipRTC = async () => {
        httpClient.post('http://localhost:8080/token/agent')
            .then((response) => {
                const token = response.data.token

                this.setState((state) => {
                    state.infobipRTC = createInfobipRtc(token, { debug: true });
                    state.infobipRTC.on(InfobipRTCEvent.CONNECTED,  event => {
                        this.setState({identity: event.identity});
                        console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
                    });
                    state.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
                        console.warn('Disconnected from Infobip RTC Cloud.');
                    });
                    state.infobipRTC.connect();
                    this.listenForIncomingApplicationCall();
                    this.loadAudioDevices();
                    return state;
                });
            })
            .catch(err => {
                console.error(err);
            });
    };

    listenForIncomingApplicationCall = () => {
        this.state.infobipRTC.on(InfobipRTCEvent.INCOMING_APPLICATION_CALL, incomingApplicationCallEvent => {
            const incomingCall = incomingApplicationCallEvent.incomingCall;
            console.log('Received incoming call from: ' + incomingCall.from());

            this.setState({
                activeCall: incomingCall,
                isIncomingCall: true,
                status: 'Incoming ' + (incomingCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingCall.from()
            });

            this.setApplicationCallEventHandlers(incomingCall);
        });
    }

    loadAudioDevices = () => {
        this.state.infobipRTC.getAudioInputDevices().then(inputDevices => this.setState({audioInputDevices: inputDevices}))
    }

    setApplicationCallEventHandlers = (call) => {
        call.on(CallsApiEvent.RINGING, () => {
            this.setState({status: 'Ringing...'});
            console.log('Call is ringing...');
        });
        call.on(CallsApiEvent.ESTABLISHED, event => {
            this.setState({status: 'Established'});
            console.log('Call is established');
            this.setMediaStream(this.refs.remoteAudio, event.stream);
            this.setState({isCallEstablished: true});
        });
        call.on(CallsApiEvent.HANGUP, event => {
            this.setState({status: 'Call finished, errorCode: ' + event.errorCode.name});
            console.log('Call finished, errorCode: ' + event.errorCode.name);
            this.setValuesAfterCall();
        });
        call.on(CallsApiEvent.ERROR, event => {
            console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        });

        call.on(CallsApiEvent.CONFERENCE_JOINED, event => {
            this.setState({status: 'Joined conference, conferenceId: ' + event.id});
            console.log('Joined conference, conferenceId: ' + event.id);
            event.participants.forEach(participant => this.addParticipant(participant.endpoint.identifier));
        });
        call.on(CallsApiEvent.CONFERENCE_LEFT, event => {
            this.setState({status: 'Left conference, errorCode: ' + event.errorCode.name});
            console.log('Left conference, errorCode: ' + event.errorCode.name);
            this.setValuesAfterLeavingConferenceOrDialog();
        });
        call.on(CallsApiEvent.DIALOG_JOINED, event => {
            this.setState({status: 'Joined dialog, dialogId: ' + event.id});
            console.log('Joined dialog, dialogId: ' + event.id);
            this.addParticipant(event.remote.endpoint.identifier);
        });
        call.on(CallsApiEvent.DIALOG_LEFT, event => {
            this.setState({status: 'Left dialog, errorCode: ' + event.errorCode.name});
            console.log('Left dialog, errorCode: ' + event.errorCode.name);
            this.setValuesAfterLeavingConferenceOrDialog();
        });

        call.on(CallsApiEvent.PARTICIPANT_JOINING, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' is joining'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' is joining');
        });
        call.on(CallsApiEvent.PARTICIPANT_JOINED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' joined'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' joined');
            this.addParticipant(event.participant.endpoint.identifier);
        });
        call.on(CallsApiEvent.PARTICIPANT_LEFT, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' left'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' left');
            this.removeParticipant(event.participant.endpoint.identifier);
        });

        call.on(CallsApiEvent.PARTICIPANT_MUTED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' is now muted'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' is now muted');
        });
        call.on(CallsApiEvent.PARTICIPANT_UNMUTED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' is now unmuted'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' is now unmuted');
        });

        call.on(CallsApiEvent.CAMERA_VIDEO_ADDED, event => {
            this.setState({status: 'Local camera video has been added'});
            console.log('Local camera video has been added');
            this.setMediaStream(this.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, event => {
            this.setState({status: 'Local camera video has been updated'});
            console.log('Local camera video has been updated');
            this.setMediaStream(this.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, () => {
            this.setState({status: 'Local camera video has been removed'});
            console.log('Local camera video has been removed');
            this.setMediaStream(this.refs.localCameraVideo, null);
        });

        call.on(CallsApiEvent.SCREEN_SHARE_ADDED, event => {
            this.setState({status: 'Local screenshare has been added'});
            console.log('Local screenshare has been added');
            this.setMediaStream(this.refs.localScreenShare, event.stream);
        });
        call.on(CallsApiEvent.SCREEN_SHARE_REMOVED, () => {
            this.setState({status: 'Local screenshare has been removed'});
            console.log('Local screenshare has been removed');
            this.setMediaStream(this.refs.localScreenShare, null);
        });

        call.on(CallsApiEvent.PARTICIPANT_CAMERA_VIDEO_ADDED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' added camera video'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' added camera video');
            this.updateParticipant(event.participant.endpoint.identifier, {camera: event.stream});
        });
        call.on(CallsApiEvent.PARTICIPANT_CAMERA_VIDEO_REMOVED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' removed camera video'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' removed camera video');
            this.updateParticipant(event.participant.endpoint.identifier, {camera: null});
        });
        call.on(CallsApiEvent.PARTICIPANT_SCREEN_SHARE_ADDED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' added screenshare'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' added screenshare');
            this.updateParticipant(event.participant.endpoint.identifier, {screenShare: event.stream});
        });
        call.on(CallsApiEvent.PARTICIPANT_SCREEN_SHARE_REMOVED, event => {
            this.setState({status: 'Participant ' + event.participant.endpoint.identifier + ' removed screenshare'});
            console.log('Participant ' + event.participant.endpoint.identifier + ' removed screenshare');
            this.updateParticipant(event.participant.endpoint.identifier, {screenShare: null});
        });

        call.on(CallsApiEvent.NETWORK_QUALITY_CHANGED, event => {
            console.log('Local network quality has changed: ' + NetworkQuality[event.networkQuality]);
        });
        call.on(CallsApiEvent.PARTICIPANT_NETWORK_QUALITY_CHANGED, event => {
            console.log('Network quality of ' + event.participant.endpoint.identifier + ' has changed: ' + NetworkQuality[event.networkQuality]);
        });

        call.on(CallsApiEvent.RECONNECTING, () => {
            this.setState({status: 'Reconnecting...'});
            console.log('Reconnecting...');
        });
        call.on(CallsApiEvent.RECONNECTED, () => {
            this.setState({status: 'Established'});
            console.log('Reconnected');
        });
        call.on(CallsApiEvent.PARTICIPANT_DISCONNECTED, event => {
            console.log("Participant " + event.participant.endpoint.identifier + " disconnected");
        });
        call.on(CallsApiEvent.PARTICIPANT_RECONNECTED, event => {
            console.log("Participant " + event.participant.endpoint.identifier + " reconnected");
        });
    }

    accept = () => {
        this.state.activeCall.accept(
            ApplicationCallOptions.builder()
                .setVideo(true)
                .setAutoReconnect(true)
                .build()
        );
    };

    decline = () => {
        this.state.activeCall.decline();
    };

    hangup = () => {
        this.state.activeCall.hangup();
    };

    setValuesAfterCall = () => {
        this.setState({
            activeCall: null,
            status: '',
            isIncomingCall: false,
            isCallEstablished: false,
            selectedAudioQualityMode: 'Auto'
        });
    }

    setValuesAfterLeavingConferenceOrDialog = () => {
        this.participants = [];
    }

    setMediaStream = (element, stream) => {
        element.srcObject = stream;
    }

    addParticipant = (identifier) =>
        this.setState(({participants}) => ({participants: [...participants, {identifier}]}));

    removeParticipant = identifier =>
        this.setState(({participants}) => ({participants: participants.filter(participant => participant.identifier !== identifier)}));

    updateParticipant = (identifier, fields) => {
        this.setState(({participants}) => {
            let participant = participants.find(participant => participant.identifier === identifier);
            if (participant) Object.assign(participant, fields);
            return {participants};
        });
    }

    setVideo = (element, stream) => {
        if (!element) return;
        if (stream && element.srcObject !== stream) {
            element.srcObject = stream;
        }
    }

    toggleScreenShare = () => {
        this.state.activeCall.screenShare(!this.state.activeCall.hasScreenShare())
            .catch(error => console.log('Error toggling screen share {}', error));
    }

    toggleCameraVideo = () => {
        this.state.activeCall.cameraVideo(!this.state.activeCall.hasCameraVideo())
            .catch(error => console.log('Error toggling camera video {}', error));
    }

    hasLocalVideos = () => {
        return this.state.activeCall && (this.state.activeCall.hasCameraVideo() || this.state.activeCall.hasScreenShare());
    }

    shouldShowButtonsOnIncomingCall = () => {
        return !this.state.isCallEstablished && this.state.isIncomingCall;
    };

    shouldShowCallActions = () => {
        return this.state.isCallEstablished;
    }

    onAudioInputDeviceChange = async event => {
        const deviceId = event.target.value;
        const {activeCall} = this.state;
        if (!!activeCall) {
            await activeCall.setAudioInputDevice(deviceId);
        }
    }

    onAudioQualityChange = event => {
        const audioQuality = event.target.value;
        const {activeCall} = this.state;
        this.setState({selectedAudioQualityMode: audioQuality});

        if (!!activeCall) {
            activeCall.setAudioQualityMode(audioQualityModes[audioQuality]);
        }
    }

    render = () => {
        const {
            participants,
            identity,
            status,
            activeCall,
            audioInputDevices,
            selectedAudioQualityMode
        } = this.state;

        let remoteVideos = participants.reduce((remoteVideos, participant) => [
            ...[
                {participant, video: participant.camera},
                {participant, video: participant.screenShare}
            ].filter(({video}) => video != null),
            ...remoteVideos
        ], []);

        return (
            <div>
                <h4>Logged-in as: <span>{identity}</span></h4>

                <audio ref="remoteAudio" autoPlay/>

                <div hidden={!this.shouldShowButtonsOnIncomingCall()}>
                    <button onClick={() => this.accept()}>Accept</button>
                    <button onClick={() => this.decline()}>Decline</button>
                    <br/><br/>
                </div>

                <div hidden={!this.shouldShowCallActions()}>
                    <button onClick={() => this.toggleCameraVideo()}>Toggle Camera Video</button>
                    <button onClick={() => this.toggleScreenShare()}>Toggle Screen Share</button>
                    <br/><br/>

                    <button hidden={!this.shouldShowCallActions()} onClick={() => this.hangup()}>Hangup</button>
                    <br/><br/>
                </div>

                {!!activeCall &&
                    <>
                        <label htmlFor={"audio-input-device-select"}>Choose audio input device:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioInputDeviceChange}>
                            {audioInputDevices.map(device => <option id={device.deviceId} value={device.deviceId}>{device.label || device.deviceId}</option>)}
                        </select>
                        <br/><br/>

                        <label htmlFor={"audio-input-device-select"}>Choose audio quality mode:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioQualityChange} value={selectedAudioQualityMode}>
                            {Object.keys(audioQualityModes).map(mode => <option id={mode} value={mode}>{mode}</option>)}
                        </select>
                        <br/><br/>
                    </>
                }

                <h4><span>{status}</span></h4>
                <br/><br/>

                <div hidden={activeCall && remoteVideos.length > 0 ? '' : 'hidden'}>
                    <h3>Remote videos/screenshares</h3>
                    {remoteVideos.map(({video}) => {
                        return (
                            <video
                                ref={element => this.setVideo(element, video)}
                                width="300" height="300"
                                style={{"objectFit": "cover"}}
                                autoPlay/>
                        )}
                    )}
                </div>

                <div hidden={this.hasLocalVideos() ? '' : 'hidden'}>
                    <h3>Local video/screenshare</h3>
                    <video width="300" height="300"
                           style={{"objectFit": "cover"}}
                           autoPlay
                           ref="localCameraVideo"/>
                    <video width="300" height="300"
                           style={{"objectFit": "cover"}}
                           autoPlay
                           ref="localScreenShare"/>
                    <br/><br/>
                </div>
            </div>
        )
    }
}

export default Agent;

// js/application-calls/angular/src/app/components/agent/agent.component.ts
import {Component, ViewChild} from '@angular/core';
import {
  ApplicationCall,
  ApplicationCallOptions,
  AudioQualityMode,
  CallsApiEvent,
  createInfobipRtc,
  IncomingApplicationCall,
  InfobipRTC,
  InfobipRTCEvent,
  NetworkQuality,
} from 'infobip-rtc';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-agent',
  templateUrl: './agent.component.html'
})
export class AgentComponent {
  @ViewChild('remoteAudio') remoteAudio: HTMLAudioElement;
  @ViewChild('localCameraVideo') localCameraVideo: HTMLVideoElement;
  @ViewChild('localScreenShare') localScreenShare: HTMLVideoElement;

  infobipRTC: InfobipRTC = null;
  activeCall: ApplicationCall = null;
  identity = '';
  status = '';

  isIncomingCall = false;
  isCallEstablished = false;

  participants = [];
  remoteVideos = [];

  audioInputDevices: MediaDeviceInfo[] = [];
  selectedAudioInputDevice: string;
  audioQualityModes: { [name: string]: AudioQualityMode } = {
    Low: AudioQualityMode.LOW_DATA,
    Auto: AudioQualityMode.AUTO,
    High: AudioQualityMode.HIGH_QUALITY
  }
  selectedAudioQualityMode = 'Auto';

  constructor(private httpClient: HttpClient) {
    this.connectInfobipRTC();
  }

  connectInfobipRTC() {
    this.httpClient.post('http://localhost:8080/token/agent', {})
      .toPromise()
      .then((response: Response) => {
        // @ts-ignore
        this.infobipRTC = createInfobipRtc(response.token, { debug: true });
        this.infobipRTC.on(InfobipRTCEvent.CONNECTED, event => {
          this.identity = event.identity;
          console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
        });
        this.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
          console.warn('Disconnected from Infobip RTC Cloud.');
        });
        this.infobipRTC.connect();
        this.listenForIncomingApplicationCall();
        this.loadAudioDevices()
      })
  };

  listenForIncomingApplicationCall() {
    this.infobipRTC.on(InfobipRTCEvent.INCOMING_APPLICATION_CALL, incomingCallEvent => {
      const incomingApplicationCall = incomingCallEvent.incomingCall;
      console.log('Received incoming call from: ' + incomingApplicationCall.from());

      this.activeCall = incomingApplicationCall;
      this.listenForApplicationCallEvents();

      this.isIncomingCall = true;
      this.status = 'Incoming ' + (incomingApplicationCall.options().video ? 'video' : 'audio') +
        ' call from: ' + incomingApplicationCall.from();
    });
  };

  loadAudioDevices = () => {
    this.infobipRTC.getAudioInputDevices().then(inputDevices => {
      this.audioInputDevices = inputDevices;
      this.selectedAudioInputDevice = inputDevices[0].deviceId
    });
  }

  listenForApplicationCallEvents() {
    this.activeCall.on(CallsApiEvent.RINGING, () => {
      this.status = 'Ringing...';
      console.log('Call is ringing...');
    });
    this.activeCall.on(CallsApiEvent.ESTABLISHED, event => {
      this.status = 'Established';
      console.log('Call is established');
      this.setMediaStream(this.remoteAudio, event.stream);
      this.isCallEstablished = true;
    });
    this.activeCall.on(CallsApiEvent.HANGUP, event => {
      this.status = 'Call finished, errorCode: ' + event.errorCode.name;
      console.log('Call finished, errorCode: ' + event.errorCode.name);
      this.removeAllMediaStreams();
      this.setValuesAfterCall();
    });
    this.activeCall.on(CallsApiEvent.ERROR, event => {
      console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
    });

    this.activeCall.on(CallsApiEvent.CONFERENCE_JOINED, event => {
      this.status = 'Joined conference, conferenceId: ' + event.id;
      console.log('Joined conference, conferenceId: ' + event.id);

      event.participants.forEach((participant) => this.addParticipant(participant.endpoint.identifier));
    });
    this.activeCall.on(CallsApiEvent.CONFERENCE_LEFT, event => {
      this.status = 'Left conference, errorCode: ' + event.errorCode.name;
      console.log('Left conference, errorCode: ' + event.errorCode.name);
      this.setValuesAfterLeavingConferenceOrDialog();
    });
    this.activeCall.on(CallsApiEvent.DIALOG_JOINED, event => {
      this.status = 'Joined dialog, dialogId: ' + event.id;
      console.log('Joined dialog, dialogId: ' + event.id);
      this.addParticipant(event.remote.endpoint.identifier);
    });
    this.activeCall.on(CallsApiEvent.DIALOG_LEFT, event => {
      this.status = 'Left dialog, errorCode: ' + event.errorCode.name;
      console.log('Left dialog, errorCode: ' + event.errorCode.name);
      this.setValuesAfterLeavingConferenceOrDialog();
    });

    this.activeCall.on(CallsApiEvent.PARTICIPANT_JOINING, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' is joining';
      console.log('Participant ' + event.participant.endpoint.identifier + ' is joining');
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_JOINED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' joined';
      console.log('Participant ' + event.participant.endpoint.identifier + ' joined');
      this.addParticipant(event.participant.endpoint.identifier);
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_LEFT, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' left';
      console.log('Participant ' + event.participant.endpoint.identifier + ' left');
      this.removeParticipant(event.participant.endpoint.identifier);
    });

    this.activeCall.on(CallsApiEvent.PARTICIPANT_MUTED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' is now muted';
      console.log('Participant ' + event.participant.endpoint.identifier + ' is now muted');
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_UNMUTED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' is now unmuted';
      console.log('Participant ' + event.participant.endpoint.identifier + ' is now unmuted');
    });

    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_ADDED, event => {
      this.status = 'Participant added local camera video';
      console.log('Participant added local camera video');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, event => {
      this.status = 'Participant updated local camera video';
      console.log('Participant updated local camera video');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, () => {
      this.status = 'Participant removed local camera video';
      console.log('Participant removed local camera video');
      this.setMediaStream(this.localCameraVideo, null);
    });

    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_ADDED, event => {
      this.status = 'Participant added local screenshare';
      console.log('Participant added local screenshare');
      this.setMediaStream(this.localScreenShare, event.stream);
    });
    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_REMOVED, () => {
      this.status = 'Participant removed local screenshare';
      console.log('Participant removed local screenshare');
      this.setMediaStream(this.localScreenShare, null);
    });

    this.activeCall.on(CallsApiEvent.PARTICIPANT_CAMERA_VIDEO_ADDED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' added camera video';
      console.log('Participant ' + event.participant.endpoint.identifier + ' added camera video');
      this.updateParticipant(event.participant.endpoint.identifier, {camera: event.stream});
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_CAMERA_VIDEO_REMOVED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' removed camera video';
      console.log('Participant ' + event.participant.endpoint.identifier + ' removed camera video');
      this.updateParticipant(event.participant.endpoint.identifier, {camera: null});
    });

    this.activeCall.on(CallsApiEvent.PARTICIPANT_SCREEN_SHARE_ADDED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' added screenshare';
      console.log('Participant ' + event.participant.endpoint.identifier + ' added screenshare');
      this.updateParticipant(event.participant.endpoint.identifier, {screenShare: event.stream});
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_SCREEN_SHARE_REMOVED, event => {
      this.status = 'Participant ' + event.participant.endpoint.identifier + ' removed screenshare';
      console.log('Participant ' + event.participant.endpoint.identifier + ' removed screenshare');
      this.updateParticipant(event.participant.endpoint.identifier, {screenShare: null});
    });

    this.activeCall.on(CallsApiEvent.NETWORK_QUALITY_CHANGED, event => {
      console.log('Local network quality has changed: ' + NetworkQuality[event.networkQuality]);
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_NETWORK_QUALITY_CHANGED, event => {
      console.log('Network quality of ' + event.participant.endpoint.identifier + ' has changed: ' + NetworkQuality[event.networkQuality]);
    });

    this.activeCall.on(CallsApiEvent.RECONNECTING, () => {
      this.status = 'Reconnecting...';
      console.log('Reconnecting...');
    });
    this.activeCall.on(CallsApiEvent.RECONNECTED, () => {
      this.status = 'Established';
      console.log('Reconnected');
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_DISCONNECTED, event => {
      console.log('Participant ' + event.participant.endpoint.identifier + ' disconnected');
    });
    this.activeCall.on(CallsApiEvent.PARTICIPANT_RECONNECTED, event => {
      console.log('Participant ' + event.participant.endpoint.identifier + ' reconnected');
    });
  };

  hangup() {
    this.activeCall.hangup();
  };

  setValuesAfterCall() {
    this.status = null;
    this.activeCall = null;
    this.isCallEstablished = false;
    this.isIncomingCall = false;
    this.selectedAudioQualityMode = 'Auto';
  }

  setValuesAfterLeavingConferenceOrDialog() {
    this.participants = [];
    this.remoteVideos = [];
  }

  removeAllMediaStreams() {
    // @ts-ignore
    this.remoteAudio.nativeElement.srcObject = null;
    // @ts-ignore
    this.localCameraVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.localScreenShare.nativeElement.srcObject = null;
  }

  setMediaStream(element, stream) {
    element.nativeElement.srcObject = stream;
  }

  toggleScreenShare() {
    this.activeCall.screenShare(!this.activeCall.hasScreenShare())
      .catch(error => console.log('Error toggling screen share {}', error));
  }

  toggleCameraVideo() {
    this.activeCall.cameraVideo(!this.activeCall.hasCameraVideo())
      .catch(error => console.log('Error toggling camera video {}', error));
  }

  addParticipant(identifier) {
    this.participants.push({identifier});
  }

  removeParticipant(identifier) {
    this.participants = this.participants.filter(participant => participant.identifier !== identifier);
  }

  updateParticipant(identifier, fields) {
    const participantToUpdate = this.participants.find(participant => participant.identifier === identifier);
    if (participantToUpdate) Object.assign(participantToUpdate, fields);
    this.updateRemoteVideos();
  }

  updateRemoteVideos() {
    this.remoteVideos = this.participants.reduce((remoteVideos, participant) => [
      ...[
        {participant, video: participant.camera},
        {participant, video: participant.screenShare}
      ].filter(({video}) => video != null),
      ...remoteVideos
    ], []);
  }

  shouldShowLocalVideos() {
    return this.activeCall && (this.activeCall.hasCameraVideo() || this.activeCall.hasScreenShare());
  }

  shouldShowRemoteVideos() {
    return this.activeCall && this.remoteVideos.length > 0
  }

  accept() {
    (this.activeCall as IncomingApplicationCall).accept(
      ApplicationCallOptions.builder().setVideo(true).setAutoReconnect(true).build()
    );
  };

  decline() {
    (this.activeCall as IncomingApplicationCall).decline();
  };

  shouldShowButtonsOnIncomingCall() {
    return !this.isCallEstablished && this.isIncomingCall;
  };

  shouldShowCallActions() {
    return this.isCallEstablished;
  }

  onAudioInputDeviceChange = async () => {
    if (this.activeCall != null) {
      await this.activeCall.setAudioInputDevice(this.selectedAudioInputDevice)
    }
  }

  onAudioQualityChange = () => {
    if (this.activeCall != null) {
      this.activeCall.setAudioQualityMode(this.audioQualityModes[this.selectedAudioQualityMode])
    }
  }
}

<div>
  <div>
    <h4>Logged-in as: <span>{{identity || 'None'}}</span></h4>
  </div>

  <audio #remoteAudio autoPlay></audio>

  <div [hidden]="!shouldShowButtonsOnIncomingCall()">
    <button (click)="accept()">Accept</button>
    <button (click)="decline()">Decline</button>
    <br/><br/>
  </div>

  <div [hidden]="!shouldShowCallActions()">
    <button (click)="toggleCameraVideo()">Toggle Camera Video</button>
    <button (click)="toggleScreenShare()">Toggle Screen Share</button>
    <br/><br/>

    <button (click)="hangup()">Hangup</button>
    <br/><br/>
  </div>

  <ng-container *ngIf="!!activeCall">
    <label for="audio-input-device-select">Choose audio input device:</label>
    <select id="audio-input-device-select" [(ngModel)]="selectedAudioInputDevice" (change)="onAudioInputDeviceChange()">
      <option *ngFor="let device of audioInputDevices" [value]="device.deviceId">{{device.label || device.deviceId}}</option>
    </select>
    <br/><br/>

    <label for="audio-quality-mode-select">Choose audio quality mode:</label>
    <select id="audio-quality-mode-select" [(ngModel)]="selectedAudioQualityMode" (change)="onAudioQualityChange()">
      <option *ngFor="let mode of audioQualityModes | keyvalue" [value]="mode.key">{{mode.key}}</option>
    </select>
    <br/><br/>
  </ng-container>

  <h4><span>{{status}}</span></h4>
  <br/><br/>

  <div [hidden]="!shouldShowRemoteVideos()">
    <h3>Remote videos/screenshares</h3>
    <video *ngFor="let videoElement of remoteVideos"
           [srcObject]="videoElement.video"
           width="300" height="300"
           style="object-fit: cover" autoPlay>
    </video>
  </div>

  <div [hidden]="!shouldShowLocalVideos()">
    <h3>Local video/screenshare</h3>
    <video #localCameraVideo autoplay muted
           style="object-fit: cover"
           width="300" height="300">
    </video>
    <video #localScreenShare autoplay
           style="object-fit: cover"
           width="300" height="300">
    </video>
  </div>
</div>
