// js/react/src/Call.js
import React, {Component} from "react";
import {CallOptions, CallPhoneNumberOptions, InfobipRTC} from "infobip-rtc";
import httpClient from "axios";

class Call extends Component {

    constructor(props) {
        super(props);
        this.state = {
            title: 'Infobip RTC Call Showcase',
            destination: '',
            infobipRTC: null,
            activeCall: null,
            identity: '',
            status: '',
            isCallEstablished: false,
            isOutgoingCall: false,
            isIncomingCall: false,
            isIphoneOrIpad: !!(window.navigator.userAgent.match(/iPad/i) || window.navigator.userAgent.match(/iPhone/i))
        };

        this.connectInfobipRTC();
    }

    connectInfobipRTC = async () => {
        httpClient.post('http://localhost:8080/token')
            .then((response) => {
                const token = response.data.token

                this.setState((state) => {
                    state.infobipRTC = new InfobipRTC(token, {debug: true});
                    state.infobipRTC.on('connected',  (event) => {
                        this.setState({identity: event.identity});
                        console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
                    });
                    state.infobipRTC.on('disconnected', function (event) {
                        console.warn('Disconnected from Infobip RTC Cloud.');
                    });
                    state.infobipRTC.connect();
                    this.listenForIncomingCall();
                    return state;
                });
            })
            .catch(err => {
                console.error(err);
            });
    };

    listenForIncomingCall() {
        let that = this;
        this.state.infobipRTC.on('incoming-call', function (incomingCallEvent) {
            const incomingCall = incomingCallEvent.incomingCall;
            console.log('Received incoming call from: ' + incomingCall.source().identity);

            that.setState({
                activeCall: incomingCall,
                isIncomingCall: true,
                status: 'Incoming ' + (incomingCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingCall.source().identity
            });
            incomingCall.on('established', event => {
                that.setMediaStream(incomingCall, event);
                that.setState({
                    status: 'In a call with: ' + incomingCall.source().identity,
                    isCallEstablished: true
                });
            });
            incomingCall.on('updated', event => {
                that.setMediaStream(incomingCall, event);
            });
            incomingCall.on('hangup', () => {
                that.removeMediaStream();
                that.setValuesAfterIncomingCall();
            });
            incomingCall.on('error', (event) => {
                console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
                that.removeMediaStream();
                that.setValuesAfterIncomingCall();
            });
        });
    }

    setCallEventHandlers(call) {
        let that = this;
        call.on('established', function (event) {
            that.setState({status: 'Call established with: ' + that.state.destination});
            console.log('Call established with ' + that.state.destination);
            that.setMediaStream(call, event);
        });
        call.on('hangup', function (event) {
            that.removeMediaStream();
            that.setValuesAfterOutgoingCall();
            that.setState({status: 'Call finished, status: ' + event.status.description});
        });
        call.on('ringing', function () {
            that.setState({status: 'Ringing...'});
            console.log('Call is ringing...');
        });
        call.on('updated', function (event) {
            that.setMediaStream(call, event);
        });
        call.on('error', function (event) {
            console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
            that.removeMediaStream();
            that.setValuesAfterOutgoingCall();
        });
    }

    setMediaStream(call, event) {
        if (call.hasLocalVideo()) {
            this.refs.localVideo.srcObject = event.localStream;
        } else {
            this.refs.localVideo.srcObject = null;
        }

        if(call.hasRemoteVideo()) {
            this.refs.remoteVideo.srcObject = event.remoteStream;
            this.refs.remoteAudio.srcObject = null;
        } else {
            this.refs.remoteVideo.srcObject = null;
            this.refs.remoteAudio.srcObject = event.remoteStream;
        }
    }

    removeMediaStream() {
        this.refs.localVideo.srcObject = null;
        this.refs.remoteVideo.srcObject = null;
        this.refs.remoteAudio.srcObject = null;
    }

    handleChange = (event) => {
        const dest = event.target.value;
        this.setState({destination: dest});
    };

    call = (video = false) => {
        if (this.state.destination) {
            let callOptions = CallOptions.builder()
                .setVideo(video)
                .build();

            const activeCall = this.state.infobipRTC.call(this.state.destination, callOptions);
            this.setCallEventHandlers(activeCall);
            this.setState({
                activeCall: activeCall,
                isOutgoingCall: true
            });
        }
    };

    callPhoneNumber = () => {
        if (this.state.destination) {
            let callPhoneNumberOptions = CallPhoneNumberOptions.builder()
                .setFrom('33712345678')
                .build();
            const activeCall = this.state.infobipRTC.callPhoneNumber(this.state.destination, callPhoneNumberOptions);
            this.setCallEventHandlers(activeCall);
            this.setState({
                activeCall: activeCall,
                isOutgoingCall: true
            });
        }
    };

    accept = () => {
        this.state.activeCall.accept();
    };

    decline = () => {
        this.state.activeCall.decline();
    };

    hangup = () => {
        this.state.activeCall.hangup();
    };

    shouldDisableButtonsOnIncomingCall() {
        return this.state.isCallEstablished || this.state.isOutgoingCall || !this.state.isIncomingCall;
    }

    shouldDisableHangupButton() {
        return !this.state.activeCall || (!this.state.isCallEstablished && this.state.isIncomingCall);
    }

    setValuesAfterIncomingCall() {
        this.setState({
            status: null,
            activeCall: null,
            isCallEstablished: false,
            isIncomingCall: false
        });
    }

    setValuesAfterOutgoingCall() {
        this.setState({
            activeCall: null,
            isOutgoingCall: false
        });
    }

    render() {

        return (
            <div>
                <h2><span>{this.state.title}</span></h2>
                <h4>Logged as: <span>{this.state.identity}</span></h4>
                <audio ref="remoteAudio" autoPlay/>
                <input type="text" value={this.state.destination} onChange={this.handleChange}
                       placeholder="Enter destination to call..."/>
                <br/> <br/>
                <button disabled={this.state.activeCall} onClick={() => this.call(false)}>Call</button>
                <button disabled={this.state.activeCall} onClick={() => this.call(true)}>Video Call</button>
                <button disabled={!this.state.activeCall}
                        onClick={() => this.state.activeCall.screenShare(!this.state.activeCall.hasScreenShare())}>
                        Toggle Screen Share </button>
                <button disabled={this.state.activeCall} onClick={this.callPhoneNumber}>Call Phone Number</button>
                <br/><br/>

                <h4><span>{this.state.status}</span></h4>
                <button
                    disabled={this.shouldDisableButtonsOnIncomingCall()}
                    onClick={this.accept}>Accept
                </button>
                <button
                    disabled={this.shouldDisableButtonsOnIncomingCall()}
                    onClick={this.decline}>Decline
                </button>
                <br/><br/>
                <button disabled={this.shouldDisableHangupButton()}
                        onClick={this.hangup}>Hangup
                </button>
                <br/><br/>

                {this.state.isIphoneOrIpad && (<button onClick={() => { this.refs.remoteVideo.muted = false }}>Tap to Unmute</button>)}
                <br/><br/>

                <video width="700" height="700"
                       style={{"object-fit": "cover"}}
                       autoPlay
                       muted={this.state.isIphoneOrIpad}
                       ref="remoteVideo"/>

                <video width="700" height="700"
                       style={{"object-fit": "cover"}}
                       autoPlay muted
                       ref="localVideo"/>
            </div>
        )
    }
}

export default Call;

// js/angular/src/app/components/call/call.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {Call, CallOptions, CallPhoneNumberOptions, IncomingCall, InfobipRTC} from 'infobip-rtc';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-call',
  templateUrl: './call.component.html'
})
export class CallComponent implements OnInit {
  @ViewChild('remoteAudio') remoteAudio: HTMLAudioElement;
  @ViewChild('remoteVideo') remoteVideo: HTMLVideoElement;
  @ViewChild('localVideo') localVideo: HTMLVideoElement;

  title = 'Infobip RTC Call Showcase';

  destination = '';
  infobipRTC: InfobipRTC = null;
  activeCall: Call = null;
  identity = '';
  status = '';
  isCallEstablished = false;
  isOutgoingCall = false;
  isIncomingCall = false;
  iPhoneOrIpad = false;

  constructor(private httpClient: HttpClient) {
    this.connectInfobipRTC();
  }

  ngOnInit(): void {
    const userAgent = window.navigator.userAgent;
    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
      this.iPhoneOrIpad = true;
      // @ts-ignore
      this.remoteVideo.nativeElement.muted = true;
    }
  }

  unmuteVideo = () => {
    // @ts-ignore
    this.remoteVideo.nativeElement.muted = false;
  }

  connectInfobipRTC = () => {
    this.httpClient.post('http://localhost:8080/token', {})
      .toPromise()
      .then((response: Response) => {
        // @ts-ignore
        this.infobipRTC = new InfobipRTC(response.token, {debug: true});
        this.infobipRTC.on('connected', event => {
          this.identity = event.identity;
          console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
        });
        this.infobipRTC.on('disconnected', event => {
          console.warn('Disconnected from Infobip RTC Cloud.');
        });
        this.infobipRTC.connect();
        this.listenForIncomingCall();
      })
  };

  listenForIncomingCall = () => {
    this.infobipRTC.on('incoming-call', incomingCallEvent => {
      const incomingCall = incomingCallEvent.incomingCall;
      console.log('Received incoming call from: ' + incomingCall.source().identity);

      this.activeCall = incomingCall;
      this.isIncomingCall = true;
      this.status = 'Incoming ' + (incomingCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingCall.source().identity;

      incomingCall.on('established', event => {
        this.setMediaStream(incomingCall, event);
        this.status = 'In a call with: ' + incomingCall.source().identity;
        this.isCallEstablished = true;
      });
      incomingCall.on('hangup', () => {
        this.removeMediaStream();
        this.setValuesAfterIncomingCall();
      });
      incomingCall.on('updated', event => {
        this.setMediaStream(incomingCall, event);
      });
      incomingCall.on('error', event => {
        console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        this.removeMediaStream();
        this.setValuesAfterIncomingCall();
      });
    });
  };

  listenForCallEvents = () => {
    if (this.activeCall) {
      this.activeCall.on('established', event => {
        this.status = 'Call established with: ' + this.destination;
        console.log('Call established with ' + this.destination);

        // @ts-ignore
        that.setMediaStream(this.activeCall, event);
      });
      this.activeCall.on('hangup', event => {
        this.removeMediaStream();
        this.setValuesAfterOutgoingCall();
      });
      this.activeCall.on('ringing', () => {
        this.status = 'Ringing...';
        console.log('Call is ringing...');
      });
      this.activeCall.on('updated', event => {
        this.setMediaStream(this.activeCall, event);
      });
      this.activeCall.on('error', event => {
        console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        this.removeMediaStream();
        this.setValuesAfterOutgoingCall();
      });
    }
  };

  removeMediaStream() {
    // @ts-ignore
    this.localVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteAudio.nativeElement.srcObject = null;
  }

  setMediaStream = (call, event) => {
    if (call.hasLocalVideo()) {
      // @ts-ignore
      this.localVideo.nativeElement.srcObject = event.localStream;
    } else {
      // @ts-ignore
      this.localVideo.nativeElement.srcObject = null;
    }

    if(call.hasRemoteVideo()) {
      // @ts-ignore
      this.remoteVideo.nativeElement.srcObject = event.remoteStream;
      // @ts-ignore
      this.remoteAudio.nativeElement.srcObject = null;
    } else {
      // @ts-ignore
      this.remoteVideo.nativeElement.srcObject = null;
      // @ts-ignore
      this.remoteAudio.nativeElement.srcObject = event.remoteStream;
    }
  }

  onChange = (event) => {
    this.destination = event.target.value;
  };

  call = (video = false) => {
    if (this.destination) {
      const callOptions = CallOptions.builder()
        .setVideo(video)
        .build();

      this.activeCall = this.infobipRTC.call(this.destination, callOptions);
      this.isOutgoingCall = true;

      this.listenForCallEvents();
    }
  };

  callPhoneNumber = () => {
    if (this.destination) {
      const callPhoneNumberOptions = CallPhoneNumberOptions.builder()
        .setFrom('33712345678')
        .build();
      this.activeCall = this.infobipRTC.callPhoneNumber(this.destination, callPhoneNumberOptions);

      this.listenForCallEvents();
    }
  };

  hangup = () => {
    this.activeCall.hangup();
  };

  accept = () => {
    (this.activeCall as IncomingCall).accept();
  };

  decline = () => {
    (this.activeCall as IncomingCall).decline();
  };

  shouldDisableButtonsOnIncomingCall = () => {
    return this.isCallEstablished || this.isOutgoingCall || !this.isIncomingCall;
  };

  shouldDisableHangupButton = () => {
    return !this.activeCall || (!this.isCallEstablished && this.isIncomingCall);
  };

  toggleShareScreen = () => {
    this.activeCall.screenShare(!this.activeCall.hasScreenShare());
  }

  private setValuesAfterIncomingCall() {
    this.status = null;
    this.activeCall = null;
    this.isCallEstablished = false;
    this.isIncomingCall = false;
  }

  private setValuesAfterOutgoingCall() {
    this.status = null;
    this.activeCall = null;
    this.isOutgoingCall = false;
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Infobip RTC Showcase</title>
</head>
<body>
<div>
  <h2>{{title}}</h2>
  <h4>Logged as: <span>{{identity || 'None'}}</span></h4>
</div>
<div>
  <audio #remoteAudio autoPlay></audio>
  <input type="text" (change)="onChange($event)" placeholder="Enter destination to call..."/>
  <br/> <br/>
  <button [disabled]="activeCall" (click)="call(false)">Call</button>
  <button [disabled]="activeCall" (click)="call(true)">Video Call</button>
  <button [disabled]="!activeCall" (click)="toggleShareScreen()">Toggle Share Screen</button>
  <button [disabled]="activeCall" (click)="callPhoneNumber()">Call Phone Number</button>
  <br/><br/>

  <h4><span>{{status}}</span></h4>
  <button [disabled]="shouldDisableButtonsOnIncomingCall()" (click)="accept()">Accept</button>
  <button [disabled]="shouldDisableButtonsOnIncomingCall()" (click)="decline()">Decline</button>
  <br/><br/>

  <button [disabled]="shouldDisableHangupButton()" (click)="hangup()">Hangup</button>
  <br/><br/>

  <div *ngIf="iPhoneOrIpad">
    <button (click)="unmuteVideo()">Tap to Unmute</button>
    <br/><br/>
  </div>

  <video #remoteVideo autoplay
         style="object-fit: cover"
         width="700" height="700">
  </video>
  <video #localVideo autoplay muted
         style="object-fit: cover"
         width="700" height="700">
  </video>
</div>
</body>
</html>
