// js/audio-and-video-calls/react/src/WebrtcCall.js
import React, {Component} from "react";
import {
    CallsApiEvent,
    createInfobipRtc,
    InfobipRTCEvent,
    WebrtcCallOptions,
    NetworkQuality,
    AudioQualityMode
} from "infobip-rtc";
import httpClient from "axios";

const audioQualityModes = {
    "Low": AudioQualityMode.LOW_DATA,
    "Auto": AudioQualityMode.AUTO,
    "High": AudioQualityMode.HIGH_QUALITY
}

class WebrtcCall extends Component {

    constructor(props) {
        super(props);
        this.state = {
            title: 'Infobip RTC Call Showcase',
            destination: '',
            infobipRTC: null,
            activeCall: null,
            identity: '',
            status: '',
            isIncomingCall: false,
            isCallEstablished: false,
            isIphoneOrIpad: !!(window.navigator.userAgent.match(/iPad/i) || window.navigator.userAgent.match(/iPhone/i)),
            audioInputDevices: [],
            selectedAudioQualityMode: "Auto"
        };

        this.connectInfobipRTC();
    }

    connectInfobipRTC = async () => {
        httpClient.post('http://localhost:8080/token')
            .then((response) => {
                const token = response.data.token

                this.setState((state) => {
                    state.infobipRTC = createInfobipRtc(token, {debug: true});
                    state.infobipRTC.on(InfobipRTCEvent.CONNECTED, event => {
                        this.setState({identity: event.identity});
                        console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
                    });
                    state.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
                        console.warn('Disconnected from Infobip RTC Cloud.');
                    });
                    state.infobipRTC.connect();
                    this.listenForIncomingCall();
                    this.loadAudioDevices();
                    return state;
                });
            })
            .catch(err => {
                console.error(err);
            });
    };

    loadAudioDevices = () => {
        this.state.infobipRTC.getAudioInputDevices().then(inputDevices => this.setState({audioInputDevices: inputDevices}));
    }

    listenForIncomingCall = () => {
        this.state.infobipRTC.on(InfobipRTCEvent.INCOMING_WEBRTC_CALL, incomingCallEvent => {
            const incomingCall = incomingCallEvent.incomingCall;
            console.log('Received incoming call from: ' + incomingCall.counterpart().identifier);

            this.setState({
                activeCall: incomingCall,
                isIncomingCall: true,
                status: 'Incoming ' + (incomingCall.options.video ? 'video' : 'audio') + ' call from: ' + incomingCall.counterpart().identifier
            });

            this.setCallEventHandlers(incomingCall);
        });
    }

    setCallEventHandlers = (call) => {
        call.on(CallsApiEvent.RINGING, () => {
            this.setState({status: 'Ringing...'});
            console.log('Call is ringing...');
        });
        call.on(CallsApiEvent.ESTABLISHED, event => {
            this.setState({
                status: 'Call established with: ' + this.state.activeCall.counterpart().identifier,
                isCallEstablished: true
            });
            console.log('Call established with ' + this.state.activeCall.counterpart().identifier);
            this.setMediaStream(this.refs.remoteAudio, event.stream);
        });
        call.on(CallsApiEvent.HANGUP, event => {
            this.setState({status: 'Call finished: ' + event.errorCode.name});
            console.log('Call finished: ' + event.errorCode.name);
            this.removeAllMediaStreams();
            this.setValuesAfterCall();
        });

        call.on(CallsApiEvent.ERROR, event => {
            console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
        });

        call.on(CallsApiEvent.CAMERA_VIDEO_ADDED, event => {
            this.setState({status: 'Local camera video has been added'});
            console.log('Local camera video has been added');
            this.setMediaStream(this.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, event => {
            this.setState({status: 'Local camera video has been updated'});
            console.log('Local camera video has been updated');
            this.setMediaStream(this.refs.localCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, () => {
            this.setState({status: 'Local camera video has been removed'});
            console.log('Local camera video has been removed');
            this.setMediaStream(this.refs.localCameraVideo, null);
        });

        call.on(CallsApiEvent.SCREEN_SHARE_ADDED, event => {
            this.setState({status: 'Local screenshare has been added'});
            console.log('Local screenshare has been added');
            this.setMediaStream(this.refs.localScreenShare, event.stream);
        });
        call.on(CallsApiEvent.SCREEN_SHARE_REMOVED, () => {
            this.setState({status: 'Local screenshare has been removed'});
            console.log('Local screenshare has been removed');
            this.setMediaStream(this.refs.localScreenShare, null);
        });

        call.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_ADDED, event => {
            this.setState({status: 'Remote camera video has been added'});
            console.log('Remote camera video has been added');
            this.setMediaStream(this.refs.remoteCameraVideo, event.stream);
        });
        call.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_REMOVED, () => {
            this.setState({status: 'Remote camera video has been removed'});
            console.log('Remote camera video has been removed');
            this.setMediaStream(this.refs.remoteCameraVideo, null);
        });

        call.on(CallsApiEvent.REMOTE_SCREEN_SHARE_ADDED, event => {
            this.setState({status: 'Remote screenshare has been added'});
            console.log('Remote screenshare has been added');
            this.setMediaStream(this.refs.remoteScreenShare, event.stream);
        });
        call.on(CallsApiEvent.REMOTE_SCREEN_SHARE_REMOVED, () => {
            this.setState({status: 'Remote screenshare has been removed'});
            console.log('Remote screenshare has been removed');
            this.setMediaStream(this.refs.remoteScreenShare, null);
        });

        call.on(CallsApiEvent.REMOTE_MUTED, () => {
            this.setState({status: 'Remote participant has been muted'});
            console.log('Remote participant has been muted');
        });
        call.on(CallsApiEvent.REMOTE_UNMUTED, () => {
            this.setState({status: 'Remote participant has been unmuted'});
            console.log('Remote participant has been unmuted');
        });

        call.on(CallsApiEvent.NETWORK_QUALITY_CHANGED, event => {
            console.log('Local network quality has changed: ' + NetworkQuality[event.networkQuality]);
        });
        call.on(CallsApiEvent.REMOTE_NETWORK_QUALITY_CHANGED, event => {
            console.log('Remote network quality has changed: ' + NetworkQuality[event.networkQuality]);
        });
    }

    setMediaStream = (element, stream) => {
        element.srcObject = stream;
    }

    removeAllMediaStreams = () => {
        this.refs.localCameraVideo.srcObject = null;
        this.refs.localScreenShare.srcObject = null;
        this.refs.remoteCameraVideo.srcObject = null;
        this.refs.remoteScreenShare.srcObject = null;
        this.refs.remoteAudio.srcObject = null;
    }

    handleChange = event => {
        const dest = event.target.value;
        this.setState({destination: dest});
    };

    call = (video = false) => {
        if (this.state.destination) {
            let webrtcCallOptions = WebrtcCallOptions.builder()
                .setVideo(video)
                .build();

            const activeCall = this.state.infobipRTC.callWebrtc(this.state.destination, webrtcCallOptions);
            this.setCallEventHandlers(activeCall);
            this.setState({activeCall: activeCall});
        }
    };

    accept = () => {
        this.state.activeCall.accept();
    };

    decline = () => {
        this.state.activeCall.decline();
    };

    hangup = () => {
        this.state.activeCall.hangup();
    };

    shouldShowButtonsOnIncomingCall = () => {
        return this.state.isIncomingCall && !this.state.isCallEstablished;
    }

    shouldDisableHangupButton = () => {
        return !this.state.activeCall || (!this.state.isCallEstablished && this.state.isIncomingCall);
    }

    hasLocalVideos = () => {
        return this.state.activeCall && (this.state.activeCall.hasCameraVideo() || this.state.activeCall.hasScreenShare());
    }

    hasRemoteVideos = () => {
        return this.state.activeCall && (this.state.activeCall.hasRemoteCameraVideo() || this.state.activeCall.hasRemoteScreenShare());
    }

    setValuesAfterCall = () => {
        this.setState({
            activeCall: null,
            isCallEstablished: false,
            isIncomingCall: false,
            status: '',
            selectedAudioQualityMode: "Auto"
        });
    }

    onAudioInputDeviceChange = async event => {
        const deviceId = event.target.value;
        const {activeCall} = this.state;
        if (!!activeCall) {
            await activeCall.setAudioInputDevice(deviceId);
        }
    }

    onAudioQualityChange = event => {
        const audioQuality = event.target.value;
        const {activeCall} = this.state;
        this.setState({selectedAudioQualityMode: audioQuality});

        if (!!activeCall) {
            activeCall.setAudioQualityMode(audioQualityModes[audioQuality]);
        }
    }

    render = () => {
        const {
            title,
            identity,
            destination,
            activeCall,
            status,
            isIphoneOrIpad,
            audioInputDevices,
            selectedAudioQualityMode
        } = this.state;

        return (
            <div>
                <h2><span>{title}</span></h2>
                <h4>Logged as: <span>{identity}</span></h4>

                <audio ref="remoteAudio" autoPlay/>

                <input type="text" value={destination} onChange={this.handleChange}
                       placeholder="Enter destination to call..."/>
                <br/> <br/>

                <button disabled={activeCall} onClick={() => this.call(false)}>Call</button>
                <button disabled={activeCall} onClick={() => this.call(true)}>Video Call</button>
                <br/><br/>

                <button disabled={!activeCall}
                        onClick={() => activeCall.cameraVideo(!activeCall.hasCameraVideo())}>
                    Toggle Camera Video
                </button>
                <button disabled={!activeCall}
                        onClick={() => activeCall.screenShare(!activeCall.hasScreenShare())}>
                    Toggle Screen Share
                </button>

                <h4><span>{status}</span></h4>

                {this.shouldShowButtonsOnIncomingCall() &&
                    <div>
                        <button onClick={this.accept}>Accept</button>
                        <button onClick={this.decline}>Decline</button>
                        <br/><br/>
                    </div>}

                <button disabled={this.shouldDisableHangupButton()}
                        onClick={this.hangup}>Hangup
                </button>
                <br/><br/>

                {isIphoneOrIpad && (<button onClick={() => {
                    this.refs.remoteVideo.muted = false
                }}>Tap to Unmute</button>)}

                {!!activeCall &&
                    <>
                        <label htmlFor={"audio-input-device-select"}>Choose audio input device:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioInputDeviceChange}>
                            {audioInputDevices.map(device => <option id={device.deviceId} value={device.deviceId}>{device.label || device.deviceId}</option>)}
                        </select>
                        <br/><br/>

                        <label htmlFor={"audio-input-device-select"}>Choose audio quality mode:</label>
                        <br/>
                        <select id={"audio-input-device-select"} onChange={this.onAudioQualityChange} value={selectedAudioQualityMode}>
                            {Object.keys(audioQualityModes).map(mode => <option id={mode} value={mode}>{mode}</option>)}
                        </select>
                        <br/><br/>
                    </>
                }

                <div hidden={this.hasRemoteVideos() ? '' : 'hidden'}>
                    <h3>Remote video/screenshare</h3>
                    <video ref="remoteCameraVideo" autoPlay
                           muted={isIphoneOrIpad}
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                    <video ref="remoteScreenShare" autoPlay
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                </div>

                <div hidden={this.hasLocalVideos() ? '' : 'hidden'}>
                    <h3>Local video/screenshare</h3>
                    <video ref="localCameraVideo" autoPlay muted
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                    <video ref="localScreenShare" autoPlay
                           style={{"objectFit": "cover"}}
                           width="300" height="300">
                    </video>
                </div>
            </div>
        )
    }
}

export default WebrtcCall;

// js/audio-and-video-calls/angular/src/app/components/webrtc-call/webrtc-call.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {
  AudioQualityMode,
  CallsApiEvent,
  createInfobipRtc,
  IncomingWebrtcCall,
  InfobipRTC,
  InfobipRTCEvent,
  NetworkQuality,
  WebrtcCall,
  WebrtcCallOptions
} from 'infobip-rtc';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-call',
  templateUrl: './webrtc-call.component.html'
})
export class WebrtcCallComponent implements OnInit {
  @ViewChild('remoteAudio') remoteAudio: HTMLAudioElement;
  @ViewChild('localCameraVideo') localCameraVideo: HTMLVideoElement;
  @ViewChild('localScreenShare') localScreenShare: HTMLVideoElement;
  @ViewChild('remoteCameraVideo') remoteCameraVideo: HTMLVideoElement;
  @ViewChild('remoteScreenShare') remoteScreenShare: HTMLVideoElement;

  title = 'Infobip RTC Call Showcase';

  destination = '';
  infobipRTC: InfobipRTC = null;
  activeCall: WebrtcCall = null;
  identity = '';
  status = '';
  isCallEstablished = false;
  isIncomingCall = false;
  iPhoneOrIpad = false;
  audioInputDevices: MediaDeviceInfo[] = [];
  selectedAudioInputDevice: string;
  audioQualityModes: { [name: string]: AudioQualityMode } = {
    Low: AudioQualityMode.LOW_DATA,
    Auto: AudioQualityMode.AUTO,
    High: AudioQualityMode.HIGH_QUALITY
  }
  selectedAudioQualityMode = 'Auto';

  constructor(private httpClient: HttpClient) {
    this.connectInfobipRTC();
  }

  ngOnInit = () => {
    const userAgent = window.navigator.userAgent;
    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
      this.iPhoneOrIpad = true;
      // @ts-ignore
      this.remoteCameraVideo.nativeElement.muted = true;
    }
  }

  unmuteVideo = () => {
    // @ts-ignore
    this.remoteVideo.nativeElement.muted = false;
  }

  connectInfobipRTC = () => {
    this.httpClient.post('http://localhost:8080/token', {})
      .toPromise()
      .then((response: Response) => {
        // @ts-ignore
        this.infobipRTC = createInfobipRtc(response.token, { debug: true });
        this.infobipRTC.on(InfobipRTCEvent.CONNECTED, event => {
          this.identity = event.identity;
          console.log('Connected to Infobip RTC Cloud with: %s', event.identity);
        });
        this.infobipRTC.on(InfobipRTCEvent.DISCONNECTED, event => {
          console.warn('Disconnected from Infobip RTC Cloud.');
        });
        this.infobipRTC.connect();
        this.loadAudioDevices();
        this.listenForIncomingWebrtcCall();
      })
  };

  loadAudioDevices = () => {
    this.infobipRTC.getAudioInputDevices().then(inputDevices => {
      this.audioInputDevices = inputDevices;
      this.selectedAudioInputDevice = inputDevices[0].deviceId
    });
  }

  listenForIncomingWebrtcCall = () => {
    this.infobipRTC.on(InfobipRTCEvent.INCOMING_WEBRTC_CALL, incomingCallEvent => {
      const incomingWebrtcCall = incomingCallEvent.incomingCall;
      console.log('Received incoming call from: ' + incomingWebrtcCall.source().identifier);

      this.activeCall = incomingWebrtcCall;
      this.isIncomingCall = true;
      this.status = 'Incoming ' + (incomingWebrtcCall.options().video ? 'video' : 'audio') +
        ' call from: ' + incomingWebrtcCall.source().identifier;

      this.listenForWebrtcCallEvents();
    });
  };

  listenForWebrtcCallEvents = () => {
    this.activeCall.on(CallsApiEvent.RINGING, () => {
      this.status = 'Ringing...';
      console.log('Call is ringing...');
    });
    this.activeCall.on(CallsApiEvent.ESTABLISHED, event => {
      this.status = 'Call established with: ' + this.activeCall.counterpart().identifier;
      console.log('Call established with ' + this.activeCall.counterpart().identifier);
      this.isCallEstablished = true;
      this.setMediaStream(this.remoteAudio, event.stream);
    });
    this.activeCall.on(CallsApiEvent.HANGUP, event => {
      this.status = 'Call finished' + event.errorCode.name;
      console.log('Call finished' + event.errorCode.name);
      this.removeAllMediaStreams();
      this.setValuesAfterCall();
    });
    this.activeCall.on(CallsApiEvent.ERROR, event => {
      console.log('Oops, something went very wrong! Message: ' + JSON.stringify(event));
    });

    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_ADDED, event => {
      this.status = 'Local camera video has been added';
      console.log('Local camera video has been added');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_UPDATED, event => {
      this.status = 'Local camera video has been updated';
      console.log('Local camera video has been updated');
      this.setMediaStream(this.localCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.CAMERA_VIDEO_REMOVED, () => {
      this.status = 'Local camera video has been removed';
      console.log('Local camera video has been removed');
      this.setMediaStream(this.localCameraVideo, null);
    });

    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_ADDED, event => {
      this.status = 'Local screenshare has been added';
      console.log('Local screenshare has been added');
      this.setMediaStream(this.localScreenShare, event.stream);
    });
    this.activeCall.on(CallsApiEvent.SCREEN_SHARE_REMOVED, () => {
      this.status = 'Local screenshare has been removed';
      console.log('Local screenshare has been removed');
      this.setMediaStream(this.localScreenShare, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_ADDED, event => {
      this.status = 'Remote camera video has been added';
      console.log('Remote camera video has been added');
      this.setMediaStream(this.remoteCameraVideo, event.stream);
    });
    this.activeCall.on(CallsApiEvent.REMOTE_CAMERA_VIDEO_REMOVED, () => {
      this.status = 'Remote camera video has been removed';
      console.log('Remote camera video has been added');
      this.setMediaStream(this.remoteCameraVideo, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_SCREEN_SHARE_ADDED, event => {
      this.status = 'Remote screenshare has been added';
      console.log('Remote screenshare has been added');
      this.setMediaStream(this.remoteScreenShare, event.stream);
    });
    this.activeCall.on(CallsApiEvent.REMOTE_SCREEN_SHARE_REMOVED, () => {
      this.status = 'Remote screenshare has been removed';
      console.log('Remote screenshare has been removed');
      this.setMediaStream(this.remoteScreenShare, null);
    });

    this.activeCall.on(CallsApiEvent.REMOTE_MUTED, () => {
      this.status = 'Remote participant has been muted';
      console.log('Remote participant has been muted');
    });
    this.activeCall.on(CallsApiEvent.REMOTE_UNMUTED, () => {
      this.status = 'Remote participant has been unmuted';
      console.log('Remote participant has been unmuted');
    });

    this.activeCall.on(CallsApiEvent.NETWORK_QUALITY_CHANGED, event => {
      console.log('Local network quality has changed: ' + NetworkQuality[event.networkQuality]);
    });
    this.activeCall.on(CallsApiEvent.REMOTE_NETWORK_QUALITY_CHANGED, event => {
      console.log('Remote network quality has changed: ' + NetworkQuality[event.networkQuality]);
    });
  };

  removeAllMediaStreams = () => {
    // @ts-ignore
    this.remoteAudio.nativeElement.srcObject = null;
    // @ts-ignore
    this.localCameraVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.localScreenShare.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteCameraVideo.nativeElement.srcObject = null;
    // @ts-ignore
    this.remoteScreenShare.nativeElement.srcObject = null;
  }

  setMediaStream(element, stream) {
    element.nativeElement.srcObject = stream;
  }

  onChange = (event) => {
    this.destination = event.target.value;
  };

  call = (video = false) => {
    if (this.destination) {
      const webrtcCallOptions = WebrtcCallOptions.builder()
        .setVideo(video)
        .build();

      this.activeCall = this.infobipRTC.callWebrtc(this.destination, webrtcCallOptions);

      this.listenForWebrtcCallEvents();
    }
  };

  hangup = () => {
    this.activeCall.hangup();
  };

  accept = () => {
    (this.activeCall as IncomingWebrtcCall).accept();
  };

  decline = () => {
    (this.activeCall as IncomingWebrtcCall).decline();
  };

  shouldShowButtonsOnIncomingCall = () => {
    return !this.isCallEstablished && this.isIncomingCall;
  };

  shouldDisableHangupButton = () => {
    return !this.activeCall || (!this.isCallEstablished && this.isIncomingCall);
  };

  toggleCameraVideo = () => {
    this.activeCall.cameraVideo(!this.activeCall.hasCameraVideo());
  }

  toggleScreenShare = () => {
    this.activeCall.screenShare(!this.activeCall.hasScreenShare());
  }

  private setValuesAfterCall = () => {
    this.status = null;
    this.activeCall = null;
    this.isCallEstablished = false;
    this.isIncomingCall = false;
    this.selectedAudioQualityMode = 'Auto';
  }

  shouldShowLocalVideos = () => {
    return this.activeCall && (this.activeCall.hasCameraVideo() || this.activeCall.hasScreenShare());
  }

  shouldShowRemoteVideos = () => {
    return this.activeCall && (this.activeCall.hasRemoteCameraVideo() || this.activeCall.hasRemoteScreenShare());
  }

  onAudioInputDeviceChange = async () => {
    if (this.activeCall != null) {
      await this.activeCall.setAudioInputDevice(this.selectedAudioInputDevice)
    }
  }

  onAudioQualityChange = () => {
    if (this.activeCall != null) {
      console.log('Setting audio quality mode: ', this.selectedAudioQualityMode);
      this.activeCall.setAudioQualityMode(this.audioQualityModes[this.selectedAudioQualityMode])
    }
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Infobip RTC Showcase</title>
</head>
<body>
  <div>
    <h2>{{title}}</h2>
    <h4>Logged as: <span>{{identity || 'None'}}</span></h4>
  </div>

  <audio #remoteAudio autoPlay></audio>

  <input type="text" (change)="onChange($event)" placeholder="Enter destination to call..."/>
  <br/><br/>

  <button [disabled]="activeCall" (click)="call(false)">Call</button>
  <button [disabled]="activeCall" (click)="call(true)">Video Call</button>
  <br/><br/>

  <button [disabled]="!activeCall" (click)="toggleCameraVideo()">Toggle Camera Video</button>
  <button [disabled]="!activeCall" (click)="toggleScreenShare()">Toggle Screen Share</button>

  <h4><span>{{status}}</span></h4>
  <br/><br/>

  <div [hidden]="!shouldShowButtonsOnIncomingCall()">
    <button (click)="accept()">Accept</button>
    <button (click)="decline()">Decline</button>
    <br/><br/>
  </div>

  <button [disabled]="shouldDisableHangupButton()" (click)="hangup()">Hangup</button>
  <br/><br/>

  <div *ngIf="iPhoneOrIpad">
    <button (click)="unmuteVideo()">Tap to Unmute</button>
    <br/><br/>
  </div>

  <ng-container *ngIf="!!activeCall">
    <label for="audio-input-device-select">Choose audio input device:</label>
    <select id="audio-input-device-select" [(ngModel)]="selectedAudioInputDevice" (change)="onAudioInputDeviceChange()">
      <option *ngFor="let device of audioInputDevices" [value]="device.deviceId">{{device.label || device.deviceId}}</option>
    </select>
    <br/><br/>

    <label for="audio-quality-mode-select">Choose audio quality mode:</label>
    <select id="audio-quality-mode-select" [(ngModel)]="selectedAudioQualityMode" (change)="onAudioQualityChange()">
      <option *ngFor="let mode of audioQualityModes | keyvalue" [value]="mode.key">{{mode.key}}</option>
    </select>
    <br/><br/>
  </ng-container>

  <div [hidden]="!shouldShowRemoteVideos()">
    <h3>Remote video/screenshare</h3>
    <video #remoteCameraVideo autoplay muted
           style="object-fit: cover"
           width="300" height="300">
    </video>
    <video #remoteScreenShare autoplay
           style="object-fit: cover"
           width="300" height="300">
    </video>
  </div>

  <div [hidden]="!shouldShowLocalVideos()">
    <h3>Local video/screenshare</h3>
    <video #localCameraVideo autoplay muted
           style="object-fit: cover"
           width="300" height="300">
    </video>
    <video #localScreenShare autoplay
           style="object-fit: cover"
           width="300" height="300">
    </video>
  </div>
</body>
</html>
